### ISSUE TITLE
Should noload_ext1() et al instantiate an object?

### ISSUE THREAD

**Issue by moreati** [zopefoundation/zodbpickle#40]
Tackling #21 I noticed a discrepancy. `Unpickler.noload_global()` reads the arguments from the pickle, discards them, then appends `None` to the stack. `Unpickler.noload_ext1()` (and variants) read the code from the pickle, load the object onto the stack (by calling `Unpickler.get_extension()`, then replace it on the stack with None.

Shouldn't `noload_ext1()` do the same as `noload_global()`? I.e. make no attempt load (instantiate) an object, then append `None` to the stack

**Comment by jamadden** [comment]
The [C code for noload](https://github.com/zopefoundation/zodbpickle/pull/12/files) was taken directly from Python 2.6, so that's "canonical." I *think* I made up the Python versions myself, just based on what `load` was doing, but I don't remember for sure. If there are discrepancies in the Python version that don't make sense, and that fixing doesn't break tests, I would say it's probably fine to fix them. Off hand, I don't know what those opcodes are supposed to do; the C implementation appears to bypass a lot of that.

**Comment by moreati** [comment]
They're part of the extension registry, which is used by roughly nobody AFAICT, https://github.com/moreati/pickle-fuzz#extension-registry has an example of it's use. I'll play around to see what happens.

**Comment by tseaver** [comment]
As with #41:  leaving `Py_None` on the stack in `noload_extension` doesn't matter, because we don't care about the actual objects.  We only need to be able to walk the pickle, gathering persistent IDs.
